ignorePatterns:
  - "dist"
parser: "@typescript-eslint/parser"
extends:
  - eslint:recommended
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: "module"
