version: "3"
services:
  mongodb:
    image: "bitnami/mongodb:4.4.3"
    ports:
      - "27017:27017"
    logging:
      driver: "none"
    volumes:
      - "mongodb_data:/bitnami"
volumes:
  mongodb_data:
    driver: local
