version: "3"
services:
  element-tracker:
    image: "cs124/element-tracker:latest"
    ports:
      - "8888:8888"
    environment:
      - "VALID_DOMAINS=http://localhost:3000"
      - "MONGODB=mongodb://mongodb:27017/jeed_demo"
      - "GOOGLE_CLIENT_IDS=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}"
  mongodb:
    image: "bitnami/mongodb:4.4.3"
    logging:
      driver: "none"
    volumes:
      - "mongodb_data:/bitnami"
volumes:
  mongodb_data:
    driver: local
